const columns = [
    { name: "PRODUCT NAME", uid: "product_name", sortable: true },
    { name: "CATEGORY", uid: "category", sortable: true },
    { name: "BRAND", uid: "brand", sortable: true },
    { name: "PRICE", uid: "price", sortable: true },
    { name: "QUANTITY", uid: "quantity", sortable: true },
    { name: "RETAILER", uid: "retailer", sortable: true },
    { name: "CREATED DATE", uid: "created_at", sortable: true },
    { name: "EXPIRE ON", uid: "expire_on", sortable: true },
    { name: "ACTIONS", uid: "actions" },
];

const products = [
    {
        id: 1,
        product_name: "8A (PT-925567)",
        category: 'Display',
        brand: 'Samsung',
        price: 820,
        quantity: 4,
        retailer: 'Barberry',
        created_at: "10/01/2024",
        expire_on: '01 Jan, 2024',
    },
    {
        id: 2,
        product_name: "9 Prime (PT-120488)",
        category: 'Display',
        brand: 'Samsung',
        price: 230,
        quantity: 4,
        retailer: 'Barberry',
        created_at: "10/01/2024",
        expire_on: '01 Jan, 2024',
    },
    {
        id: 3,
        product_name: "A01 Core (PT-684072)",
        category: 'Display',
        brand: 'Samsung',
        price: 820,
        quantity: 4,
        retailer: 'Barberry',
        created_at: "10/01/2024",
        expire_on: '01 Jan, 2024',
    },
    {
        id: 4,
        product_name: "A01/M01 (PT-346811)",
        category: 'Display',
        brand: 'Samsung',
        price: 230,
        quantity: 4,
        retailer: 'Barberry',
        created_at: "10/01/2024",
        expire_on: '01 Jan, 2024',

    },
    {
        id: 5,
        product_name: "8A (PT-925567)",
        category: 'Display',
        brand: 'Samsung',
        price: 820,
        quantity: 4,
        retailer: 'Barberry',
        created_at: "10/01/2024",
        expire_on: '01 Jan, 2024',
    },
    {
        id: 6,
        product_name: "9 Prime (PT-120488)",
        category: 'Display',
        brand: 'Samsung',
        price: 230,
        quantity: 4,
        retailer: 'Barberry',
        created_at: "10/01/2024",
        expire_on: '01 Jan, 2024',
    },
    {
        id: 7,
        product_name: "A01 Core (PT-684072)",
        category: 'Display',
        brand: 'Samsung',
        price: 820,
        quantity: 4,
        retailer: 'Barberry',
        created_at: "10/01/2024",
        expire_on: '01 Jan, 2024',
    },
    {
        id: 8,
        product_name: "A01/M01 (PT-346811)",
        category: 'Display',
        brand: 'Samsung',
        price: 230,
        quantity: 4,
        retailer: 'Barberry',
        created_at: "10/01/2024",
        expire_on: '01 Jan, 2024',
    },
];

export { columns, products };
